name = input('Input your name:')
address = input('Input your address:')
city = input('Input your city:')
region = input('Input your region:')
postcode = int(input('Input your postcode:'))
number_phone = int(input('Input your number phone'))
possition = input('Input your possition in univercity:')
print('Your name -', name)
print('Your address, city region and postcode -', city, region, postcode)
print('Your phone number -', number_phone)
print('Your possition in univercity -', possition)
